source 'http://rubygems.org'

gem 'rails'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'json'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

gem 'jquery-rails'
gem "bcrypt-ruby", :require => "bcrypt"
gem 'client_side_validations'
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'
gem 'execjs'
gem 'rubyzip'
gem 'therubyracer'
gem 'activerecord'
gem 'spreadsheet'
gem 'paperclip'
gem 'roo'
gem 'roadie'
gem 'tabulous'
gem 'secure_string'
gem 'rqrcode-rails3'
gem 'mini_magick'
gem "omniauth"
gem 'omniauth-facebook'
gem 'omniauth-google'
gem 'omniauth-twitter'
gem 'stripe'
gem 'paypal-recurring'
gem 'whenever', :require => false
gem 'rufus-scheduler'
gem 'validates_timeliness'
gem 'pdfkit'
gem 'wicked_pdf'
